### ISSUE TITLE
RTL support for PacmanIndicator

### ISSUE THREAD

**Issue by mtx62** [n4kz/react-native-indicators#10]
Greetings,
Kindly add rtl support for PacmanIndicator for android and IOS

![simulator screen shot - iphone x - 2018-03-20 at 12 36 33](https://user-images.githubusercontent.com/3220251/37646703-67532f88-2c3b-11e8-95f0-e2dbabcc2ee3.png)

Note: I solved this issue in IOS by adding `direction: 'ltr',` but it's not supported in Android 

Best regards.

**Comment by n4kz** [comment]
Thanks for issue! Released a fix in `0.13.0`.

**Comment by mtx62** [comment]
Thank you
