### ISSUE TITLE
'hasLoopSupport' works incorrectly

### ISSUE THREAD

**Issue by parshukovanton** [n4kz/react-native-indicators#12]
Hey,

I found in your code (indicator/index.js):

const [major, minor] = RN.version.split('.');
const hasLoopSupport = !major && minor >= 45;

hasLoopSupport is always FALSE
you have to fix it in the following way:

const hasLoopSupport = major == 0 && minor >= 45;

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Fix is available in `0.13.0`.
