### ISSUE TITLE
WaveIndicator waveMode='outline' broken in Android 7.0 RN-0.55

### ISSUE THREAD

**Issue by designingSparks** [n4kz/react-native-indicators#16]
The WaveIndicator is broken in Android 7 with waveMode='outline'. At the beginning of the animation, only the top left quadrant of the animation is displayed correctly.
waveMode='fill' works correctly.

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Please, check the latest release `0.14.0`.
