### ISSUE TITLE
Can't achieve animation presented on preview

### ISSUE THREAD

**Issue by luisgrases** [n4kz/react-native-indicators#24]
I am trying to achieve any of this animations using the PulseIndicator but I believe is not achievable: 
![image](https://user-images.githubusercontent.com/6208922/56552681-423fb480-6549-11e9-8979-616f6cd7bd72.png)

Am I missing something?

**Comment by Frixoe** [comment]
I'm having the same issue.

**Comment by milesper** [comment]
That's actually WaveIndicator. I had the same question.
