### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by BSoD38** [n4kz/react-native-indicators#26]
The Indicator component is using `componentWillReceiveProps`, which is [deprecated in the latest React versions, and will be removed in React 17](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html).

Replacing the method by `componentDidUpdate` seems to fix the issue, although I am not certain if the behaviour is the same as before.

**Comment by hugopretorius72** [comment]
Thanks @BSoD38 I have the same warning; @n4kz is this easy for you to change?

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. I've released fix in `0.14.0`.
