### ISSUE TITLE
Should we mention uses native driver in readme?

### ISSUE THREAD

**Issue by Noitidart** [n4kz/react-native-indicators#7]
Thanks for this awesome lib! The best part about it is it uses native driver for all animations. Is this correct?

If so should we mention it in readme? Because I don't touch any modules where they have anim that do not `useNativeDriver`. :)

**Comment by n4kz** [comment]
Thanks for issue, it's already mentioned there in features :)

> Native driver based animation

Can confirm that all animations in this component are based on native driver.

**Comment by Noitidart** [comment]
Ooo thanks!
