### ISSUE TITLE
Mention advantage of this over UIActivityIndicator

### ISSUE THREAD

**Issue by Noitidart** [n4kz/react-native-indicators#8]
We should maybe mention the advantage of this libs ios style indicator over UIActivityIndicator provided by `<ActivityIndicator />`. Which is we can control size here. On iOS we only get "small" and "large". (Android we can control size but it is not determinate)

**Comment by n4kz** [comment]
Thanks for issue, that's great idea! I've updated readme and added configurable size to features.

**Comment by Noitidart** [comment]
Thank you! :)
